version: "2"

services:

  ####
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9009:9000"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=@dm1n1str@tor
    volumes:
      - "./minio:/root/.minio"
      - "${PWD}:/export"
    command: "server /export"

  portainer:
    image: "portainer/portainer:latest"
    restart: always
    ports:
      - "9000:9000"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    volumes:
      - "./portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    command: "${PORTAINERSTYLE} -H unix:///var/run/docker.sock"

  watchtower:
    image: v2tec/watchtower
    restart: always
    environment:
      - "TZ=${TZ}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "--schedule @midnight --cleanup"
